name: Cypress Tests

on: [push]

jobs:
  install:
    runs-on: ubuntu-latest
    container: cypress/browsers:node14.15.0-chrome86-ff82
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          runTests: false
      # report machine parameters
      - run: npm install --legacy-peer-deps
      - run: npm run cypress info
      - run: node -p 'os.cpus()'
      - run: npm run build
      - run: npm run cypress:ci
